vscode:
  extensions:
    - codemooseus.vscode-devtools-for-chrome@0.1.1:4CDBBCqkIIJxxORGUdymMg==
    - ritwickdey.LiveServer@5.6.1:wV4LBkq6Z5s1xwf2HrB+cw==
    - formulahendry.code-runner@0.9.14:U0vUPTCchGiTYlRHpW9ljQ==