vscode:
  extensions:
    - msjsdiag.debugger-for-chrome@4.12.1:xXSEoy8/LqF/SyOtQTqrQw==
    - codemooseus.vscode-devtools-for-chrome@0.1.1:4CDBBCqkIIJxxORGUdymMg==
    - ritwickdey.LiveServer@5.6.1:wV4LBkq6Z5s1xwf2HrB+cw==